(yolo116) PS C:\Users\rfq\bio\MDA\MHGTMDA\HGTMDA> python ./src/train.py > .\RUNs_RFQ\train_t1.txt
Traceback (most recent call last):
  File "./src/train.py", line 81, in <module>
    dataset = loading()
  File "./src/train.py", line 57, in loading
    data['miRNA_disease_feature'] = pd.read_csv(args.data_dir + 'miRNA_disease_feature.csv', header=None).iloc[:,
  File "F:\miniconda3\envs\yolo116\lib\site-packages\pandas\io\parsers\readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "F:\miniconda3\envs\yolo116\lib\site-packages\pandas\io\parsers\readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "F:\miniconda3\envs\yolo116\lib\site-packages\pandas\io\parsers\readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "F:\miniconda3\envs\yolo116\lib\site-packages\pandas\io\parsers\readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "F:\miniconda3\envs\yolo116\lib\site-packages\pandas\io\common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/miRNA_disease_feature.csv'
(yolo116) PS C:\Users\rfq\bio\MDA\MHGTMDA\HGTMDA> python ./src/train.py > .\RUNs_RFQ\train_t1.txt
Traceback (most recent call last):
  File "./src/train.py", line 81, in <module>
    dataset = loading()
  File "./src/train.py", line 60, in loading
    miRNA_embedding = np.loadtxt(args.data_dir + 'data/miRNA_embedding.txt',dtype=np.float,delimiter=None,unpack=False)
  File "F:\miniconda3\envs\yolo116\lib\site-packages\numpy\lib\npyio.py", line 1338, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "F:\miniconda3\envs\yolo116\lib\site-packages\numpy\lib\npyio.py", line 975, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "F:\miniconda3\envs\yolo116\lib\site-packages\numpy\lib\_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "F:\miniconda3\envs\yolo116\lib\site-packages\numpy\lib\_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: dataset/data/miRNA_embedding.txt not found.
(yolo116) PS C:\Users\rfq\bio\MDA\MHGTMDA\HGTMDA> python ./src/train.py > .\RUNs_RFQ\train_t1.txt
Traceback (most recent call last):
  File "./src/train.py", line 150, in <module>
    t.save(model.state_dict(), "./save_model/5_fold/train_model.pth")
  File "F:\miniconda3\envs\yolo116\lib\site-packages\torch\serialization.py", line 422, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "F:\miniconda3\envs\yolo116\lib\site-packages\torch\serialization.py", line 309, in _open_zipfile_writer
    return container(name_or_buffer)
  File "F:\miniconda3\envs\yolo116\lib\site-packages\torch\serialization.py", line 287, in __init__
    super(_open_zipfile_writer_file, self).__init__(torch._C.PyTorchFileWriter(str(name)))
RuntimeError: Parent directory ./save_model/5_fold does not exist.